name: miws25

channels:
  - anaconda
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - Cython==3.0.0
  - tqdm
  - pip

  - pip:
    - partitura==1.7.0
    - SoundFile==0.12.1
    - fastdtw==0.3.4
    - python-hiddenmarkov==0.1.3
    - appdirs==1.4.4
    - ipympl==0.9.3
    - scikit-learn==1.5.1
    - jupyter==1.0.0
    - ipython==8.15.0
    - pandas==2.0.3
    - matplotlib==3.7.2
    - numpy==1.26.0
    - scipy==1.13.1
    - torch
    - torchvision
