name: miws25

channels:
  - anaconda
  - pytorch
  - defaults

dependencies:
  - python=3.11
  - Cython==3.0.8
  - tqdm
  - pip

  - pip:
    - partitura==1.7.0
    - python-rtmidi>=1.5.8
    - SoundFile==0.12.1
    - fastdtw==0.3.4
    - python-hiddenmarkov==0.1.3
    - appdirs==1.4.4
    - ipympl==0.9.3
    - scikit-learn==1.5.1
    - jupyter>=1.0.0
    - ipython>=8.15.0
    - pandas==2.0.3
    - matplotlib>=3.9.4
    - numpy==1.26.3
    - scipy==1.13.1
    - torch
    - torchvision
    - librosa>=0.10.1
    - pyaudio>=0.2.14
    - pyfluidsynth>=1.3.3
